language: android
jdk: oraclejdk8
sudo: required
dist: trusty
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
licenses:
- android-sdk-preview-license-c81a61d9
- android-sdk-license-.+
- google-gdk-license-.+
addons:
  sonarcloud:
    organization: "kaloglu-github" # the key of the org you chose at step #3
after_success:
  - ./gradlew postBeta
  - git add -u
  - git commit -m "[ci skip] version changed"
  - git branch temp-branch
  - git checkout master
  - git merge temp-branch
  - git push origin master
script:
- ./gradlew assembleFirebaseBeta --stacktrace --no-daemon
- ./gradlew crashlyticsUploadDistributionFirebaseBeta
after_script:
- sonar-scanner -Dsonar.verbose=true -X
- ./gradlew assembleFirebaseBeta coveralls
before_install:
- chmod +x gradlew
branches:
  only:
  - master
  - develop
cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
